//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaNET8.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliotecaNET8.Web.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string AccionesTitle {
            get {
                return ResourceManager.GetString("AccionesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor creado correctamente.
        /// </summary>
        public static string AutorCreadoMessageSuccess {
            get {
                return ResourceManager.GetString("AutorCreadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el autor.
        /// </summary>
        public static string AutorEliminadoMessageFail {
            get {
                return ResourceManager.GetString("AutorEliminadoMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor eliminado correctamente.
        /// </summary>
        public static string AutorEliminadoMessageSuccess {
            get {
                return ResourceManager.GetString("AutorEliminadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar múltiples autores.
        /// </summary>
        public static string AutorEliminadoMultipleMessageFail {
            get {
                return ResourceManager.GetString("AutorEliminadoMultipleMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autores eliminados correctamente.
        /// </summary>
        public static string AutorEliminadoMultipleMessageSuccess {
            get {
                return ResourceManager.GetString("AutorEliminadoMultipleMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autores.
        /// </summary>
        public static string AutoresMenuOption {
            get {
                return ResourceManager.GetString("AutoresMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen autores con este criterio.
        /// </summary>
        public static string AutoresSearchNotFound {
            get {
                return ResourceManager.GetString("AutoresSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor modificado correctamente.
        /// </summary>
        public static string AutorModificadoMessageSuccess {
            get {
                return ResourceManager.GetString("AutorModificadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por nombre, o apellidos.
        /// </summary>
        public static string AutorSearchPlaceholder {
            get {
                return ResourceManager.GetString("AutorSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría creada correctamente.
        /// </summary>
        public static string CategoriaCreadaMessageSuccess {
            get {
                return ResourceManager.GetString("CategoriaCreadaMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la categoría.
        /// </summary>
        public static string CategoriaEliminadaMessageFail {
            get {
                return ResourceManager.GetString("CategoriaEliminadaMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría eliminada correctamente.
        /// </summary>
        public static string CategoriaEliminadaMessageSuccess {
            get {
                return ResourceManager.GetString("CategoriaEliminadaMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar múltiples categorías.
        /// </summary>
        public static string CategoriaEliminadaMultipleMessageFail {
            get {
                return ResourceManager.GetString("CategoriaEliminadaMultipleMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías eliminadas correctamente.
        /// </summary>
        public static string CategoriaEliminadaMultipleMessageSuccess {
            get {
                return ResourceManager.GetString("CategoriaEliminadaMultipleMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría modificada correctamente.
        /// </summary>
        public static string CategoriaModificadaMessageSuccess {
            get {
                return ResourceManager.GetString("CategoriaModificadaMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por nombre de categoría.
        /// </summary>
        public static string CategoriaSearchPlaceholder {
            get {
                return ResourceManager.GetString("CategoriaSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias.
        /// </summary>
        public static string CategoriasMenuOption {
            get {
                return ResourceManager.GetString("CategoriasMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen categorías con este criterio.
        /// </summary>
        public static string CategoriasSearchNotFound {
            get {
                return ResourceManager.GetString("CategoriasSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente creado correctamente.
        /// </summary>
        public static string ClienteCreadoMessageSuccess {
            get {
                return ResourceManager.GetString("ClienteCreadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el cliente.
        /// </summary>
        public static string ClienteEliminadoMessageFail {
            get {
                return ResourceManager.GetString("ClienteEliminadoMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente eliminado correctamente.
        /// </summary>
        public static string ClienteEliminadoMessageSuccess {
            get {
                return ResourceManager.GetString("ClienteEliminadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar múltiples clientes.
        /// </summary>
        public static string ClienteEliminadoMultipleMessageFail {
            get {
                return ResourceManager.GetString("ClienteEliminadoMultipleMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes eliminados correctamente.
        /// </summary>
        public static string ClienteEliminadoMultipleMessageSuccess {
            get {
                return ResourceManager.GetString("ClienteEliminadoMultipleMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente modificado correctamente.
        /// </summary>
        public static string ClienteModificadoMessageSuccess {
            get {
                return ResourceManager.GetString("ClienteModificadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por nombre, teléfono, o email.
        /// </summary>
        public static string ClienteSearchPlaceholder {
            get {
                return ResourceManager.GetString("ClienteSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string ClientesMenuOption {
            get {
                return ResourceManager.GetString("ClientesMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen clientes con este criterio.
        /// </summary>
        public static string ClientesSearchNotFound {
            get {
                return ResourceManager.GetString("ClientesSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Autor.
        /// </summary>
        public static string CrearAutorButton {
            get {
                return ResourceManager.GetString("CrearAutorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Autor.
        /// </summary>
        public static string CrearAutorTitle {
            get {
                return ResourceManager.GetString("CrearAutorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string CrearButton {
            get {
                return ResourceManager.GetString("CrearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Categoría.
        /// </summary>
        public static string CrearCategoriaButton {
            get {
                return ResourceManager.GetString("CrearCategoriaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Categoría.
        /// </summary>
        public static string CrearCategoriaTitle {
            get {
                return ResourceManager.GetString("CrearCategoriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cliente.
        /// </summary>
        public static string CrearClienteButton {
            get {
                return ResourceManager.GetString("CrearClienteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cliente.
        /// </summary>
        public static string CrearClienteTitle {
            get {
                return ResourceManager.GetString("CrearClienteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Libro.
        /// </summary>
        public static string CrearLibroButton {
            get {
                return ResourceManager.GetString("CrearLibroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Libro.
        /// </summary>
        public static string CrearLibroTitle {
            get {
                return ResourceManager.GetString("CrearLibroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Préstamo.
        /// </summary>
        public static string CrearPrestamoButton {
            get {
                return ResourceManager.GetString("CrearPrestamoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Préstamo.
        /// </summary>
        public static string CrearPrestamoTitle {
            get {
                return ResourceManager.GetString("CrearPrestamoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string EliminarButton {
            get {
                return ResourceManager.GetString("EliminarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar seleccionados.
        /// </summary>
        public static string EliminarSelectedButton {
            get {
                return ResourceManager.GetString("EliminarSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe existir al menos un autor y una categoría antes de crear un libro.
        /// </summary>
        public static string ExisteAutorCategoriaCreate {
            get {
                return ResourceManager.GetString("ExisteAutorCategoriaCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe existir al menos un autor y una categoría antes de modificar un libro.
        /// </summary>
        public static string ExisteAutorCategoriaEdit {
            get {
                return ResourceManager.GetString("ExisteAutorCategoriaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe existir al menos un libro y un cliente antes de crear un préstamo.
        /// </summary>
        public static string ExisteLibroClienteCreate {
            get {
                return ResourceManager.GetString("ExisteLibroClienteCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe existir al menos un libro y un cliente antes de modificar un préstamo.
        /// </summary>
        public static string ExisteLibroClienteEdit {
            get {
                return ResourceManager.GetString("ExisteLibroClienteEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idiomas.
        /// </summary>
        public static string IdiomasMenuOption {
            get {
                return ResourceManager.GetString("IdiomasMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string InicioMenuOption {
            get {
                return ResourceManager.GetString("InicioMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libro creado correctamente.
        /// </summary>
        public static string LibroCreadoMessageSuccess {
            get {
                return ResourceManager.GetString("LibroCreadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar libros.
        /// </summary>
        public static string LibroEliminadoMessageFail {
            get {
                return ResourceManager.GetString("LibroEliminadoMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libro eliminado correctamente.
        /// </summary>
        public static string LibroEliminadoMessageSuccess {
            get {
                return ResourceManager.GetString("LibroEliminadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar múltiples libros.
        /// </summary>
        public static string LibroEliminadoMultipleMessageFail {
            get {
                return ResourceManager.GetString("LibroEliminadoMultipleMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros eliminados correctamente.
        /// </summary>
        public static string LibroEliminadoMultipleMessageSuccess {
            get {
                return ResourceManager.GetString("LibroEliminadoMultipleMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen debe ser menor a 2 MB.
        /// </summary>
        public static string LibroImageUploadSize {
            get {
                return ResourceManager.GetString("LibroImageUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libro modificado correctamente.
        /// </summary>
        public static string LibroModificadoMessageSuccess {
            get {
                return ResourceManager.GetString("LibroModificadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por título, o ISBN.
        /// </summary>
        public static string LibroSearchPlaceholder {
            get {
                return ResourceManager.GetString("LibroSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        public static string LibrosMenuOption {
            get {
                return ResourceManager.GetString("LibrosMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen libros con este criterio.
        /// </summary>
        public static string LibrosSearchNotFound {
            get {
                return ResourceManager.GetString("LibrosSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavía no hay autores.
        /// </summary>
        public static string ListaAutoresEmptyMessage {
            get {
                return ResourceManager.GetString("ListaAutoresEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Autores.
        /// </summary>
        public static string ListaAutoresTitle {
            get {
                return ResourceManager.GetString("ListaAutoresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavía no hay categorías.
        /// </summary>
        public static string ListaCategoriasEmptyMessage {
            get {
                return ResourceManager.GetString("ListaCategoriasEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Categorías.
        /// </summary>
        public static string ListaCategoriasTitle {
            get {
                return ResourceManager.GetString("ListaCategoriasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavía no hay clientes.
        /// </summary>
        public static string ListaClientesEmptyMessage {
            get {
                return ResourceManager.GetString("ListaClientesEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Clientes.
        /// </summary>
        public static string ListaClientesTitle {
            get {
                return ResourceManager.GetString("ListaClientesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavía no hay libros.
        /// </summary>
        public static string ListaLibrosEmptyMessage {
            get {
                return ResourceManager.GetString("ListaLibrosEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Libros.
        /// </summary>
        public static string ListaLibrosTitle {
            get {
                return ResourceManager.GetString("ListaLibrosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavía no hay préstamos.
        /// </summary>
        public static string ListaPrestamosEmptyMessage {
            get {
                return ResourceManager.GetString("ListaPrestamosEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Préstamos.
        /// </summary>
        public static string ListaPrestamosTitle {
            get {
                return ResourceManager.GetString("ListaPrestamosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Autor.
        /// </summary>
        public static string ModificarAutorTitle {
            get {
                return ResourceManager.GetString("ModificarAutorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string ModificarButton {
            get {
                return ResourceManager.GetString("ModificarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Categoría.
        /// </summary>
        public static string ModificarCategoriaTitle {
            get {
                return ResourceManager.GetString("ModificarCategoriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Cliente.
        /// </summary>
        public static string ModificarClienteTitle {
            get {
                return ResourceManager.GetString("ModificarClienteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Libro.
        /// </summary>
        public static string ModificarLibroTitle {
            get {
                return ResourceManager.GetString("ModificarLibroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Préstamo.
        /// </summary>
        public static string ModificarPrestamoTitle {
            get {
                return ResourceManager.GetString("ModificarPrestamoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string PaginaAnterior {
            get {
                return ResourceManager.GetString("PaginaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string PaginaSiguiente {
            get {
                return ResourceManager.GetString("PaginaSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamo creado correctamente.
        /// </summary>
        public static string PrestamoCreadoMessageSuccess {
            get {
                return ResourceManager.GetString("PrestamoCreadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el préstamo.
        /// </summary>
        public static string PrestamoEliminadoMessageFail {
            get {
                return ResourceManager.GetString("PrestamoEliminadoMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamo eliminado correctamente.
        /// </summary>
        public static string PrestamoEliminadoMessageSuccess {
            get {
                return ResourceManager.GetString("PrestamoEliminadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar múltiples préstamos.
        /// </summary>
        public static string PrestamoEliminadoMultipleMessageFail {
            get {
                return ResourceManager.GetString("PrestamoEliminadoMultipleMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamos eliminados correctamente.
        /// </summary>
        public static string PrestamoEliminadoMultipleMessageSuccess {
            get {
                return ResourceManager.GetString("PrestamoEliminadoMultipleMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamo modificado correctamente.
        /// </summary>
        public static string PrestamoModificadoMessageSuccess {
            get {
                return ResourceManager.GetString("PrestamoModificadoMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por cliente, o por título de libro.
        /// </summary>
        public static string PrestamoSearchPlaceholder {
            get {
                return ResourceManager.GetString("PrestamoSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Préstamos.
        /// </summary>
        public static string PrestamosMenuOption {
            get {
                return ResourceManager.GetString("PrestamosMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen préstamos con este criterio.
        /// </summary>
        public static string PrestamosSearchNotFound {
            get {
                return ResourceManager.GetString("PrestamosSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Autor.
        /// </summary>
        public static string VerAutorTitle {
            get {
                return ResourceManager.GetString("VerAutorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string VerButton {
            get {
                return ResourceManager.GetString("VerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Categoría.
        /// </summary>
        public static string VerCategoriaTitle {
            get {
                return ResourceManager.GetString("VerCategoriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Cliente.
        /// </summary>
        public static string VerClienteTitle {
            get {
                return ResourceManager.GetString("VerClienteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Libro.
        /// </summary>
        public static string VerLibroTitle {
            get {
                return ResourceManager.GetString("VerLibroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Préstamo.
        /// </summary>
        public static string VerPrestamoTitle {
            get {
                return ResourceManager.GetString("VerPrestamoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string VolverButton {
            get {
                return ResourceManager.GetString("VolverButton", resourceCulture);
            }
        }
    }
}
