//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaNET8.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliotecaNET8.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos deben tener un máximo de {MaxLength} caracteres.
        /// </summary>
        public static string AutorApellidosStringLength {
            get {
                return ResourceManager.GetString("AutorApellidosStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento no puede ser posterior al día presente.
        /// </summary>
        public static string AutorFechaNacimientoFuture {
            get {
                return ResourceManager.GetString("AutorFechaNacimientoFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique el nombre del autor.
        /// </summary>
        public static string AutorNombreRequired {
            get {
                return ResourceManager.GetString("AutorNombreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre {MinLength} y {MaxLength} caracteres.
        /// </summary>
        public static string AutorNombreStringLength {
            get {
                return ResourceManager.GetString("AutorNombreStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique el nombre de la categoría.
        /// </summary>
        public static string CategoriaNombreRequired {
            get {
                return ResourceManager.GetString("CategoriaNombreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría debe tener un máximo de {MaxLength} caracteres.
        /// </summary>
        public static string CategoriaNombreStringLength {
            get {
                return ResourceManager.GetString("CategoriaNombreStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los apellidos deben tener un máximo de {MaxLength} caracteres.
        /// </summary>
        public static string ClienteApellidosStringLength {
            get {
                return ResourceManager.GetString("ClienteApellidosStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique un email correcto.
        /// </summary>
        public static string ClienteEmailPattern {
            get {
                return ResourceManager.GetString("ClienteEmailPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique el nombre del cliente.
        /// </summary>
        public static string ClienteNombreRequired {
            get {
                return ResourceManager.GetString("ClienteNombreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre {MinLength} y {MaxLength} caracteres.
        /// </summary>
        public static string ClienteNombreStringLength {
            get {
                return ResourceManager.GetString("ClienteNombreStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El teléfono debe tener un máximo de {MaxLength} caracteres.
        /// </summary>
        public static string ClienteTelefonosStringLength {
            get {
                return ResourceManager.GetString("ClienteTelefonosStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de publicación no puede ser posterior al día presente.
        /// </summary>
        public static string LibroFechaPublicacionFuture {
            get {
                return ResourceManager.GetString("LibroFechaPublicacionFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ISBN debe tener un máximo de {MaxLength} caracteres.
        /// </summary>
        public static string LibroISBNStringLength {
            get {
                return ResourceManager.GetString("LibroISBNStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique el título del libro.
        /// </summary>
        public static string LibroTituloRequired {
            get {
                return ResourceManager.GetString("LibroTituloRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El título debe tener un máximo de {MaxLength} caracteres.
        /// </summary>
        public static string LibroTituloStringLength {
            get {
                return ResourceManager.GetString("LibroTituloStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de devolución no puede ser anterior a la fecha del préstamo.
        /// </summary>
        public static string PrestamoFechaDevolucionAnterior {
            get {
                return ResourceManager.GetString("PrestamoFechaDevolucionAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique la fecha de préstamo.
        /// </summary>
        public static string PrestamoFechaPrestamoRequired {
            get {
                return ResourceManager.GetString("PrestamoFechaPrestamoRequired", resourceCulture);
            }
        }
    }
}
